//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebYalex
{
    using System;
    using System.Collections.Generic;
    
    public partial class alquileres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public alquileres()
        {
            this.contratos = new HashSet<contratos>();
        }
    
        public int id_alquiler { get; set; }
        public int id_cliente { get; set; }
        public decimal costoalquiler { get; set; }
        public string estado { get; set; }
        public int id_vehiculo { get; set; }
        public string inicio_alquiler { get; set; }
        public string finalizacion_alquiler { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual vehiculo vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contratos> contratos { get; set; }
    }
}
