//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebYalex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contratos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contratos()
        {
            this.entrega = new HashSet<entrega>();
        }
    
        public int id_contrato { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_cliente { get; set; }
        public int id_alquiler { get; set; }
        public int dias { get; set; }
        public decimal precio { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public string referencia { get; set; }
        public string tipo_pago { get; set; }
        public string num_referencia { get; set; }
        public decimal total_renta { get; set; }
        public int id_vehiculo { get; set; }
    
        public virtual alquileres alquileres { get; set; }
        public virtual clientes clientes { get; set; }
        public virtual vehiculo vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<entrega> entrega { get; set; }
    }
}
