//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebYalex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        public int id_reserva { get; set; }
        public int id_cliente { get; set; }
        public int id_vehiculo { get; set; }
        public decimal costoestimado { get; set; }
        public int id_empleado { get; set; }
        public string hora { get; set; }
        public string fecha { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual vehiculo vehiculo { get; set; }
    }
}
